#!/bin/bash 
sudo dnf copr enable atim/i3status-rust
sudo dnf install -y make automake \
gcc gcc-c++ kernel-devel \
curl git xclip shellcheck \
alacritty scrot python3-ansible-lint \
cargo protobuf-compiler rofi xautolock \
podman podman-docker jetbrains-mono-fonts \
i3status-rust

if [ ! -f ~/bin/nvm.sh ]; then
	echo "Install nvm"
	curl -s -o ~/bin/nvm.sh https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
	. "$HOME/bin/nvm.sh"
fi

export NVM_DIR="$HOME/.nvm" && source "$HOME/.bashrc"
echo "downloading npm and installing some LSPs"
nvm install --lts
npm i -g typescript typescript-language-server
npm i -g vim-language-server
npm i -g bash-language-server
npm i -g @ansible/ansible-language-server

./install-go
