#!/bin/bash
sleep 3
i3-msg '[workspace="^(1|2|3)"] move workspace to output DisplayPort-7'
i3-msg "workspace 4; move workspace to output DisplayPort-6"
i3-msg "restart"
xset s off -dpms && notify-send "Disabled DPMS"
